version: '3.2'

services:
   ytdl-api-server:
     image: registry.gitlab.com/kimvanwyk/ytdl_api_server
     restart: always
     ports:
       - "9200:80"
     volumes:
       - ./ytdl_api_server_db:/db
